# Generated by Django 3.0.2 on 2020-07-13 16:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course_table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Course_Name', models.CharField(max_length=250)),
                ('Faculty', models.CharField(max_length=250)),
                ('class_date', models.DateField()),
                ('class_time', models.TimeField()),
                ('Fee', models.FloatField()),
                ('Duration', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='EnrollCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Course_Name', models.CharField(max_length=250)),
                ('contact_number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='StudentEnrollCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=250)),
                ('phone', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Student_register',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_number', models.IntegerField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
